version: "3.0"
services:
  mysql:
    image: mysql:8.0
    ports:
    - 3306:3306
    volumes:
    - /var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DB_NAME
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_USER_PASSWORD
  mysql_helper:
    image: flyway/flyway:9.1.2-alpine
    depends_on:
      - mysql
    volumes:
      - ./db/table:/flyway/sql
    environment:
      FLYWAY_SCHEMAS: $MYSQL_DB_NAME
      FLYWAY_CLEAN_DISABLED: "false"
      FLYWAY_USER: root
      FLYWAY_PASSWORD: $MYSQL_ROOT_PASSWORD
      FLYWAY_URL: jdbc:mysql://mysql:3306?allowPublicKeyRetrieval=true
      FLYWAY_VALIDATE_MIGRATION_NAMING: "true"
      FLYWAY_TABLE: migrate
    command: ["-?"]



