USE rest_api_db;
CREATE TABLE ADDRESS(
ID int PRIMARY KEY NOT NULL,
USER_ID int NOT NULL,
ZIPCODE varchar(7),
ADDRESS varchar(50),
CREATE_TS datetime DEFAULT CURRENT_TIMESTAMP,
UPDATE_TS datetime ON UPDATE CURRENT_TIMESTAMP);
