USE rest_api_db;
CREATE TABLE USER(
ID int PRIMARY KEY NOT NULL,
NAME varchar(30),
AGE int,
EMAIL varchar(30),
CREATE_TS datetime DEFAULT CURRENT_TIMESTAMP,
UPDATE_TS datetime ON UPDATE CURRENT_TIMESTAMP);
